server:
  port: 8801

spring:
  application:
    name: users

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    should-unregister-on-shutdown: false

feign:
  hystrix:
    enabled: true