server:
  port: 8801

spring:
  application:
    name: users
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
resilience4j:
  circuitbreaker:
    instances:
      complainsClientcreateComplaint:
        minimumNumberOfCalls: 2
  timelimiter:
    instances:
      complainsClientcreateComplaint:
        timeoutDuration: 10s

eureka:
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 30
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka,http://localhost:8762/eureka
    should-unregister-on-shutdown: false