spring:
  application:
    name: Eureca
server:
  port: 8761
eureka:
  server:
    enable-self-preservation: false
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8762/eureka